# Generated by Django 3.1.6 on 2021-02-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Muzicki', 'Muzicki'), ('Filmski', 'Filmski'), ('Likovni', 'Likovni'), ('Plesni', 'Plesni'), ('Kulinarski', 'Kulinarski')], default='Muzicki', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('event_img', models.URLField(default='#')),
            ],
        ),
    ]
