# Generated by Django 3.1.7 on 2021-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventTest', '0002_auto_20210218_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_place', models.CharField(max_length=20)),
            ],
        ),
    ]
