# Generated by Django 3.1.7 on 2021-02-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventTest', '0003_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventTest.stage'),
        ),
    ]
